refactor(acknowledgement-screen): change Acknowledgement screen
apartofme/apartofme-saferplace pull request #109
Opened 2022-09-21 15:16 UTC by VladislavRiabko

- rework Acknowledgement to VerticalSwipe

2022-09-22 10:00 UTC, Reykjavik151 requested changes

2022-09-22 10:00 UTC, Reykjavik151 commented on app/screens/Onboarding/Parents/LanguageSelection/LanguageSelection.tsx
> +          nextRouteParams: 'OnboardingCarousel',
`nextRouteName`

2022-09-23 15:07 UTC, emberglaz requested changes

2022-09-23 15:07 UTC, emberglaz commented on app/components/VerticalSwipeView/VerticalSwipeView.tsx
> +import { useNavigation } from '@react-navigation/native';
move to top

2022-09-24 22:11 UTC, Reykjavik151 approved these changes

2022-09-24 22:11 UTC, merged