feat(radio-button-list) UX & logic
apartofme/apartofme-saferplace pull request #13
Opened 2022-08-29 16:06 UTC by VladislavRiabko

- add RadioButtonList 
- add types of RadioButtonList

2022-08-29 16:30 UTC, emberglaz requested changes

2022-08-29 16:30 UTC, emberglaz commented on app/components/RadioButtonList/RadioButtonList.data.ts
> +}
refactor

2022-08-29 16:30 UTC, emberglaz commented on app/components/RadioButtonList/RadioButtonList.styles.ts
> +  },
use `generalStyles.flex`

2022-08-29 16:30 UTC, emberglaz commented on app/components/RadioButtonList/RadioButtonList.tsx
> +import { IRadioButtonItem, RadioButtonListType } from './RadioButtonList.data';
`IRadioButtonListItem`

2022-08-29 16:30 UTC, emberglaz commented on app/components/RadioButtonList/RadioButtonList.tsx
> +  const [selectedItem, setSelectedItem] = useState<string>();
remove

2022-08-29 16:30 UTC, emberglaz commented on app/components/RadioButtonList/RadioButtonList.tsx
> +    ({ item }: { item: IRadioButtonItem }) => {
`IRadioButtonListItem`

2022-08-29 16:30 UTC, emberglaz commented on app/components/RadioButtonList/RadioButtonList.tsx
> +        setSelectedItem(item.title);
rename `onSelectedItemPress` or `onSelectedRadioButtonPress`

2022-08-29 16:30 UTC, emberglaz commented on app/components/RadioButtonList/RadioButtonList.tsx
> +      const onPressSelectedItems = () => {
the same

2022-08-29 16:30 UTC, emberglaz commented on app/components/RadioButtonList/RadioButtonList.tsx
> +          setSelectedItems(_.without<string>(selectedItems, deleteType));
remove `<string>`

2022-08-29 16:30 UTC, emberglaz commented on app/components/RadioButtonList/RadioButtonList.tsx
> +        const deleteType = _.find<string>(
remove `<string>`

2022-08-29 16:30 UTC, emberglaz commented on app/components/RadioButtonList/RadioButtonList.tsx
> +              : onPressSelectedItems
refactor

2022-08-29 16:30 UTC, emberglaz commented on app/components/RadioButtonList/RadioButtonList.tsx
> +      <FlatList data={data} renderItem={renderItem} />
where keyExtractor ?

2022-08-30 12:28 UTC, emberglaz approved these changes

2022-08-30 12:30 UTC, Reykjavik151 approved these changes

2022-08-30 12:30 UTC, merged