refactor(quest-nicknames)
apartofme/apartofme-saferplace pull request #134
Opened 2022-10-03 19:16 UTC by akhlivnoy

* modify useParseTextWithNickname custom hook
* add useRenderQuestHeader custom hook
* add saveChosenNickname action

2022-10-03 19:41 UTC, emberglaz approved these changes

2022-10-04 09:13 UTC, Reykjavik151 requested changes

2022-10-04 09:13 UTC, Reykjavik151 commented on app/hooks/quest.ts
> +}) => {
type it properly with our React.FC or ExtendedText usage, you can do it without objects, because you are returning JSX object as I see

2022-10-04 09:13 UTC, Reykjavik151 commented on app/hooks/quest.ts
> +};
change file to `.tsx` and just use JSX (its analog of React.createElement)

2022-10-04 09:13 UTC, Reykjavik151 commented on app/screens/Reusable/Acknowledgement/AcknowledgementAlongEdges/AcknowledgementAlongEdges.tsx
> +            })}
Hook should be here, I think you should use it before JSX and then put it as <YourVariableNameFromUppercasedLetter prop1 prop2 prop3 />

2022-10-04 09:13 UTC, Reykjavik151 commented on app/screens/Reusable/Acknowledgement/AcknowledgementNicknames/AcknowledgementNicknames.tsx
>                <ExtendedText preset="secondary-text" style={styles.description}>
the same as above

2022-10-04 09:13 UTC, Reykjavik151 commented on app/screens/Reusable/Acknowledgement/AcknowledgementSuccessively/AcknowledgementSuccessively.tsx
> +            })}
the same as above

2022-10-04 09:13 UTC, Reykjavik151 commented on app/screens/Reusable/Acknowledgement/AcknowledgementSuccessively/AcknowledgementSuccessively.tsx
> +          {useRenderQuestHeader(crossHeader ?? false)}
the same as above

2022-10-04 09:13 UTC, Reykjavik151 commented on app/screens/Reusable/Acknowledgement/AcknowledgementSupport/AcknowledgementSupport.tsx
> +          {useRenderQuestHeader(crossHeader ?? false)}
the same as above

2022-10-04 09:13 UTC, Reykjavik151 commented on app/screens/Reusable/CharmCompleted/CharmCompleted.tsx
> +          })}
the same as above x2

2022-10-04 09:13 UTC, Reykjavik151 commented on app/screens/Reusable/Dialog/Dialog.tsx
> +        {useRenderQuestHeader(crossHeader ?? false)}
the same as above

2022-10-04 09:13 UTC, Reykjavik151 commented on app/screens/Reusable/EmojiSelection/EmojiSelection.tsx
> +          })}
the same as above x2

2022-10-04 09:13 UTC, Reykjavik151 commented on app/screens/Reusable/PassPhone/PassPhone.tsx
>            <Image source={IMAGES.WHITE_PENCIL} style={styles.avatar} />
the same as above x2

2022-10-04 09:13 UTC, Reykjavik151 commented on app/screens/Reusable/RadioButton/RadioButton.tsx
> +          </ExtendedText>
the same as above x2

2022-10-04 09:13 UTC, Reykjavik151 commented on app/screens/Reusable/SelectDrawBuild/SelectDrawBuild.tsx
>          <BottomButtonView
the same as above

2022-10-04 09:13 UTC, Reykjavik151 commented on app/screens/Reusable/SelectPlayer/SelectPlayer.tsx
> +        {useRenderQuestHeader(crossHeader ?? false)}
the same as above

2022-10-04 09:13 UTC, Reykjavik151 commented on app/screens/Reusable/SelectPlayerSupport/SelectPlayerSupport.tsx
>            <BottomButtonView
the same as above

2022-10-04 09:13 UTC, Reykjavik151 commented on app/screens/Reusable/Timers/CharmTimerButton/CharmTimerButton.tsx
> +        {useRenderQuestHeader(crossHeader ?? false)}
the same as above

2022-10-04 09:13 UTC, Reykjavik151 commented on app/screens/Reusable/Timers/CharmTimerTitle/CharmTimerTitle.tsx
> +          })}
the same as above x3

2022-10-04 09:13 UTC, Reykjavik151 commented on app/screens/Reusable/VerticalSwipe/VerticalSwipe.tsx
> +                  {useRenderQuestHeader(crossHeader ?? false)}
the same as above

2022-10-04 11:33 UTC, Reykjavik151 requested changes

2022-10-04 11:33 UTC, Reykjavik151 commented on app/hooks/quest.tsx
> +import { ExtendedTextPresets } from '../components/ExtendedText/ExtendedText.presets';
Can we make import from `components`?

2022-10-04 11:53 UTC, merged