feat(manage-profiles-screen): UX & navigation
apartofme/apartofme-saferplace pull request #144
Opened 2022-10-06 23:51 UTC by VladislavRiabko

- add ManageProfiles screen 
- add UserImageTitle component

2022-10-07 16:03 UTC, Reykjavik151 requested changes

2022-10-07 16:03 UTC, Reykjavik151 commented on app/screens/Menu/ManageProfiles/ManageProfiles.tsx
> +  );
Refactor it with common interface
+ make separate images for avatars @emberglaz

2022-10-07 16:03 UTC, Reykjavik151 commented on app/screens/Menu/ManageProfiles/ManageProfiles.tsx
> +            />
TODO's for all `_.noop` expressions

2022-10-11 10:26 UTC, emberglaz requested changes

2022-10-11 10:26 UTC, emberglaz commented on app/assets/images/index.ts
> +export type AvatarsNames = keyof typeof AVATAR_IMAGES;
move to utils
create enum
`enum AvatarsNameType {Logo = 'LOGO'}`

2022-10-11 10:26 UTC, emberglaz commented on app/screens/Menu/ManageProfiles/ManageProfiles.tsx
> +    state => state.user.parent?.avatar as AvatarsNames,
here it should be immediately typed strictly
if it talks about the possibility of the null type, use the operator "?"

2022-10-11 10:26 UTC, emberglaz commented on app/screens/Menu/ManageProfiles/components/UserImageTitle/UserImageTitle.types.ts
> +  image: keyof typeof IMAGES;
`AvatarsNameType`

2022-10-11 10:26 UTC, emberglaz commented on app/assets/images/index.ts
> +export type AvatarsNames = keyof typeof AVATAR_IMAGES;
and modify IUser models

2022-10-11 21:00 UTC, Reykjavik151 approved these changes

2022-10-11 21:00 UTC, merged