feat(planting-plant-flow): Garden & MaxingElixir stacks
apartofme/apartofme-saferplace pull request #149
Opened 2022-10-07 15:37 UTC by emberglaz

* add images
* add IPlant model
* add GardenStackNavigator
* add MixingElixirStackNavigator
* add updatePlantArea action in chaseSlice
* add GardenScreen UX, positioning & navigation
* add GardenTutorialDialogScreen UX, positioning & navigation
* add Plant component UX, positioning
* add PlantArea component UX, positioning
* add ElixirAnimationScreen UX, positioning & navigation
* add ElixirInstructionScreen UX, positioning & navigation
* add MixingElixirSuccessScreen UX, positioning & navigation
* remove ElixirAnimationScreen
* remove ElixirButtonScreen

2022-10-07 15:53 UTC, Reykjavik151 requested changes

2022-10-07 15:53 UTC, Reykjavik151 commented on app/models/IPlant.ts
> +  plantArea: keyof typeof PlantAreaType;
you can use enum directly: `image: PlantsType;`

2022-10-07 15:53 UTC, Reykjavik151 commented on app/navigation/stacks/mixingElixirStackNavigator.tsx
> +    selectedPlantArea: keyof typeof PlantAreaType;
the same - why do we need `keyof typeof` for enums?

2022-10-07 15:53 UTC, Reykjavik151 commented on app/redux/slices/cacheSlice.ts
> +  },
`TODO: make it as separate slice`

2022-10-07 15:53 UTC, Reykjavik151 commented on app/redux/slices/cacheSlice.ts
> +    },
The same `TODO:` comment

2022-10-07 15:53 UTC, Reykjavik151 commented on app/redux/types/cacheTypes.ts
> +export type IPlantArea = Record<keyof typeof PlantAreaType, Nullable<IPlant>>;
the same -- we need use `enum` without `keyof typeof`

2022-10-07 15:53 UTC, Reykjavik151 commented on app/screens/Garden/Garden/Garden.tsx
> +    }
Please clarify this logic for me

2022-10-07 15:53 UTC, Reykjavik151 commented on app/screens/Garden/Garden/Garden.tsx
> +    useState<Nullable<keyof typeof PlantAreaType>>(null);
the same as above

2022-10-07 15:53 UTC, Reykjavik151 commented on app/screens/Garden/GardenTutorialDialog/GardenTutorialDialog.tsx
> +    const onSabmit = useCallback(() => {
`onsAbmit` typing mistake

2022-10-07 15:53 UTC, Reykjavik151 commented on app/screens/Garden/GardenTutorialDialog/GardenTutorialDialog.tsx
> +        initialIdx={isStart ? 0 : 7}
make indexes with constants

2022-10-07 15:53 UTC, Reykjavik151 commented on app/screens/Garden/components/Plant/Plant.styles.ts
> +    zIndex: 1000,
use just `100`

2022-10-07 15:53 UTC, Reykjavik151 commented on app/screens/Garden/components/Plant/Plant.tsx
> +      source={plantImage ? plantImage : IMAGES.LOGO}
plantImage ?? IMAGES.LOGO

2022-10-07 15:53 UTC, Reykjavik151 commented on app/screens/Garden/components/PlantArea/PlantArea.tsx
> +                <Plant
Refactor it with `render...` function + params

2022-10-07 15:53 UTC, Reykjavik151 commented on app/screens/Garden/components/PlantArea/PlantArea.types.ts
> +  setActivePlantArea: (value: Nullable<keyof typeof PlantAreaType>) => void;
the same as above

2022-10-07 15:53 UTC, Reykjavik151 commented on app/screens/MixingElixir/ElixirAnimation/ElixirAnimation.tsx
> +      }
we don't need to wrap each `case` with `{}`

2022-10-07 15:53 UTC, Reykjavik151 commented on app/screens/MixingElixir/ElixirAnimation/ElixirAnimation.tsx
> +      }
if (...) {
logic 1
return
}

logic 2

2022-10-07 15:53 UTC, Reykjavik151 commented on app/screens/MixingElixir/ElixirAnimation/ElixirAnimation.tsx
> +  const getCorrectTitleKey = useCallback(() => {
refactor it with `useMemo`

2022-10-07 15:53 UTC, Reykjavik151 commented on app/screens/MixingElixir/ElixirInsrtuction/ElixirInstruction.tsx
> +        }
Refactor `case` without `{}`

2022-10-07 15:53 UTC, Reykjavik151 commented on app/screens/MixingElixir/MixingElixirSuccess/MixingElixirSuccess.tsx
> +        screen: 'Garden',
spaceline after `dispatch`

2022-10-07 15:53 UTC, Reykjavik151 commented on app/utils/types.ts
> +  SPOUR_COMPASSION = 'SPOUR_COMPASSION',
SpourCompassion = 'SPOUR_COMPASSION'

2022-10-07 16:09 UTC, emberglaz commented on app/screens/MixingElixir/ElixirAnimation/ElixirAnimation.tsx
> +      }
🐍

2022-10-10 13:26 UTC, Reykjavik151 requested changes

2022-10-10 13:26 UTC, Reykjavik151 commented on app/screens/Garden/components/PlantArea/PlantArea.styles.ts
> +    backgroundColor: 'red',
remove

2022-10-10 13:26 UTC, Reykjavik151 commented on app/screens/Garden/components/PlantArea/PlantArea.styles.ts
> +    width: WINDOW_HEIGHT < 600 ? 212 / 1.5 : 212,
WINDOW_HEIGHT < 600 to variable

2022-10-10 13:26 UTC, Reykjavik151 commented on app/screens/Garden/components/PlantArea/PlantArea.styles.ts
> +    left: WINDOW_HEIGHT < 600 ? 55 : 0,
the same as above

2022-10-10 13:26 UTC, Reykjavik151 commented on app/screens/Garden/components/PlantArea/PlantArea.tsx
> +              additionalStyles && [...additionalStyles],
`additionalStyles,`

2022-10-10 13:26 UTC, Reykjavik151 commented on app/screens/Garden/components/PlantArea/PlantArea.tsx
> +      additionalStyles?: ViewStyle[],
ViewStyle[] | ViewStyle

2022-10-10 13:26 UTC, Reykjavik151 commented on app/screens/Garden/components/PlantArea/PlantArea.tsx
> +            additionalStyles && [...additionalStyles],
the same as above

2022-10-10 13:26 UTC, Reykjavik151 commented on app/screens/Garden/components/PlantArea/PlantArea.tsx
> +          ])}
the same as above

2022-10-10 13:30 UTC, Reykjavik151 approved these changes

2022-10-10 13:30 UTC, merged