feat(slider): UX & logic
apartofme/apartofme-saferplace pull request #15
Opened 2022-08-30 14:32 UTC by VladislavRiabko

- add change color logic
https://user-images.githubusercontent.com/78753210/187464561-cd660e96-d275-4676-9701-c87fa0bb55f1.mp4

2022-08-30 14:32 UTC, VladislavRiabko commented
https://user-images.githubusercontent.com/78753210/187464878-6eeb5a78-e563-4a15-a21d-ba2c5d47d6e4.mp4

2022-08-30 15:01 UTC, emberglaz requested changes

2022-08-30 15:01 UTC, emberglaz commented on app/components/EmojiSlider/EmojiSlider.tsx
> +  const correctColor = useCallback(() => {
rename `getEmojiImage`

2022-08-31 10:03 UTC, emberglaz approved these changes

2022-08-31 12:38 UTC, Reykjavik151 approved these changes

2022-08-31 12:38 UTC, merged