feat(favourite-charm-carousel): reusable FavouriteCharmCarouselScreen UX & navigation & positioning
apartofme/apartofme-saferplace pull request #150
Opened 2022-10-07 16:44 UTC by akhlivnoy

2022-10-11 10:19 UTC, emberglaz requested changes

2022-10-11 10:19 UTC, emberglaz commented on app/screens/Reusable/FavouriteCharmCarousel/FavouriteCharmCarousel.tsx
> +export const FavouriteCharmCarouselScreen: React.FC<IFavouriteCharmCarouselScreenProps> =
refactor imports

2022-10-12 14:28 UTC, Reykjavik151 requested changes

2022-10-12 14:28 UTC, Reykjavik151 commented on app/components/FavouriteCharmCarousel/components/FavouriteCharmCarouselItem/FavouriteCharmCarouselItem.tsx
> +    });
put it into one line
```
return { backgroundColor };

2022-10-12 15:09 UTC, merged