feat(emotion-carousel-screen)
apartofme/apartofme-saferplace pull request #157
Opened 2022-10-11 20:02 UTC by akhlivnoy

* add EmotionCarousel component UX & positioning
* add EmotionCarouselScreen UX & navigation & positioning
* modify useParsedJSXTextNickname hook
* add saveEmotionItem action

2022-10-12 14:24 UTC, Reykjavik151 requested changes

2022-10-12 14:24 UTC, Reykjavik151 commented on app/hooks/quest.tsx
> +      style={{ fontWeight: '700' }}>
use `commonStyles` (create for bold text)
do not use inline styles even inside hooks

2022-10-13 10:30 UTC, emberglaz approved these changes

2022-10-13 23:04 UTC, Reykjavik151 requested changes

2022-10-13 23:04 UTC, Reykjavik151 commented on app/hooks/quest.tsx
> +    };
move it to `commonStyles`

2022-10-14 11:12 UTC, merged