feat(parent-grounding-start-screen): UX & navigation
apartofme/apartofme-saferplace pull request #162
Opened 2022-10-12 21:07 UTC by VladislavRiabko

- add GroundingStartScreen

2022-10-13 10:28 UTC, emberglaz requested changes

2022-10-13 10:28 UTC, emberglaz commented on app/screens/DummyQuests/DummyQuests.tsx
>  import { useAppDispatch, useAppSelector, useMount } from '../../hooks';
refactor imports

2022-10-13 10:28 UTC, emberglaz commented on app/screens/DummyQuests/DummyQuests.tsx
> +        },
create const obj

ComingSoon is removed

2022-10-14 15:38 UTC, Reykjavik151 approved these changes

2022-10-14 15:47 UTC, merged