feat(parent-grounding-instruction-screen): UX & navigation
apartofme/apartofme-saferplace pull request #163
Opened 2022-10-12 22:32 UTC by VladislavRiabko

- add GroundingInstructionScreen

2022-10-13 10:25 UTC, emberglaz requested changes

2022-10-13 10:25 UTC, emberglaz commented on app/screens/Grounding/General/Instruction/GroundingInstruction.types.ts
> +}
in StackNavigator : 
```
Params:
GroundingInstruction: { buttonTitle: string; }
```

2022-10-13 10:25 UTC, emberglaz commented on app/screens/Grounding/General/Instruction/GroundingInstruction.types.ts
> +}
remove

2022-10-14 15:37 UTC, Reykjavik151 approved these changes

2022-10-14 15:37 UTC, merged