feat(save-user-progress)
apartofme/apartofme-saferplace pull request #168
Opened 2022-10-13 19:07 UTC by emberglaz

* rename quest.ts -> initialQuest.ts
* add questSaga
* add plantSaga
* modify plantSlice + actions
* modify questSlice + actions
* add firestoreCreateUserProgress
* add firestoreUpdareUserProgress

2022-10-13 19:08 UTC, emberglaz commented
You can only update completely all states

2022-10-13 23:00 UTC, Reykjavik151 requested changes

2022-10-13 23:00 UTC, Reykjavik151 commented on app/constants/progress.ts
> +  TopLeft: null,
spaceline

2022-10-13 23:00 UTC, Reykjavik151 commented on app/redux/slices/questSlice.ts
> +    },
```
setQuestState(
state,
{ payload },
) {
_.merge(state, payload);
}

2022-10-13 23:00 UTC, Reykjavik151 commented on app/sagas/quest.ts
> +  );
create `selector` function, and use it as
```
const blablabla: SelectorReturnObjectName = yield select(selectorFunction);
```

2022-10-13 23:00 UTC, Reykjavik151 commented on app/sagas/quest.ts
> +    state => state.quest.completedQuestsId,
the same as above

2022-10-13 23:00 UTC, Reykjavik151 commented on app/sagas/quest.ts
> +
the same as above

2022-10-13 23:00 UTC, Reykjavik151 commented on app/sagas/quest.ts
> +  );
the same as above

2022-10-13 23:00 UTC, Reykjavik151 commented on app/sagas/quest.ts
> +  );
the same as above

2022-10-13 23:00 UTC, Reykjavik151 commented on app/screens/MixingElixir/MixingElixirSuccess/MixingElixirSuccess.tsx
> +        ] as PlantsType,
if plantsStack is empty --> error
refactor

2022-10-14 10:35 UTC, Reykjavik151 requested changes

2022-10-14 10:35 UTC, Reykjavik151 commented on app/sagas/quest.ts
> +  );
`yield select(questStateSelector);`

2022-10-14 10:43 UTC, merged