feat(charm-book-menu-ui)
apartofme/apartofme-saferplace pull request #200
Opened 2022-10-23 21:13 UTC by akhlivnoy

2022-10-23 21:43 UTC, emberglaz requested changes

2022-10-23 21:43 UTC, emberglaz commented on app/assets/images/index.ts
>    MENU: require('./backgrounds/menuBackground.png'),
we have alternativeGardenBackground.png
return gardenBackground.png and pull develop

2022-10-23 21:43 UTC, emberglaz commented on app/screens/Garden/CharmBookMenu/SkipCharm/SkipCharmEmojiSelection/SkipCharmEmojiSelection.tsx
> +import { styles } from './SkipCharmEmojiSelection.styles';
refactor imports

2022-10-24 00:13 UTC, Reykjavik151 approved these changes

2022-10-24 00:13 UTC, merged