feat(charms-introducing-screen): UX & navigation
apartofme/apartofme-saferplace pull request #23
Opened 2022-08-31 17:49 UTC by VladislavRiabko

- refactor Carousel component
- add CharmsIntroducing screen

2022-08-31 17:58 UTC, emberglaz requested changes

2022-08-31 17:58 UTC, emberglaz commented on app/components/Carousel/Carousel.props.ts
> +  setIndex?: (item: number) => void;
`setCurrentPosition`

2022-08-31 17:58 UTC, emberglaz commented on app/components/Carousel/Carousel.tsx
> +  setIndex,
the same

2022-08-31 17:58 UTC, emberglaz commented on app/screens/Onboarding/Parents/CharmsIntroducing/CharmsIntroducing.tsx
> +            setIndex={setIndex}
the same

2022-08-31 17:58 UTC, emberglaz commented on app/screens/Onboarding/Parents/CharmsIntroducing/CharmsIntroducing.tsx
> +    const [index, setIndex] = useState<number>(0);
the same

2022-08-31 17:58 UTC, emberglaz commented on app/services/localization/languages/en.ts
> +    next: 'NEXT',
`next: 'Next'`

2022-08-31 17:58 UTC, emberglaz commented on app/screens/Onboarding/Parents/CharmsIntroducing/CharmsIntroducing.tsx
> +            index > ABSOLUTE_PROGRESS_VALUE ? 'buttons.ready' : 'buttons.next',
`(index > ABSOLUTE_PROGRESS_VALUE ? 'buttons.ready' : 'buttons.next').toUpperCase()`

2022-08-31 18:08 UTC, Reykjavik151 requested changes

2022-08-31 18:08 UTC, Reykjavik151 commented on app/components/Carousel/Carousel.props.ts
> +  setCurrenPosition?: (item: number) => void;
rename `setCurrentPossition`

2022-08-31 18:08 UTC, Reykjavik151 commented on app/components/Carousel/components/ImageSubTitle/ImageSubTitle.tsx
> +      {data.subTitle && <ExtendedText>{t(data.subTitle)}</ExtendedText>}
use `data.subTitleID` if you will translate this value

2022-08-31 18:08 UTC, Reykjavik151 commented on app/components/Carousel/components/ImageTitleSubTitle/ImageTitleSubTitle.tsx
> +      {data.subTitle && <ExtendedText>{t(data.subTitle)}</ExtendedText>}
the same as above

2022-08-31 18:08 UTC, Reykjavik151 commented on app/screens/Onboarding/Parents/CharmsIntroducing/CharmsIntroducing.tsx
> +      <SafeAreaView style={[generalStyles.whFlex]}>
array?

2022-08-31 18:08 UTC, Reykjavik151 commented on app/services/localization/languages/en.ts
> +        carousel: {
let's remove `carousel` from this screen translation
so from charms_introducing.carousel.first -> charms_introducing.first

2022-09-01 09:53 UTC, Reykjavik151 approved these changes

2022-09-01 09:53 UTC, merged