feat(avatar-carouse): avatar carousel & navigation & localization
apartofme/apartofme-saferplace pull request #29
Opened 2022-09-02 14:33 UTC by VladislavRiabko

- add OnlyImage component 
- add new preset on Carousel component 
- rename subTitleID to subtitleKey
- rename titleID to titleKey
- refactor ParentsOnboardingStackNavigator 
- fix disable logic button on LanguageSelectionScreen

2022-09-02 15:43 UTC, Reykjavik151 requested changes

2022-09-02 15:43 UTC, Reykjavik151 commented on app/screens/Onboarding/Parents/LanguageSelection/LanguageSelection.tsx
> +    const onConfirm = useCallback(() => {
rename to `onSubmit`

2022-09-02 15:43 UTC, Reykjavik151 commented on app/screens/Onboarding/Parents/OnboardingCarousel/OnboardingCarousel.data.ts
> +export const CHARMS_CAROUSEL: ICarouselItem[] = [
ReadonlyArray?

2022-09-02 15:43 UTC, Reykjavik151 commented on app/screens/Onboarding/Parents/OnboardingCarousel/OnboardingCarousel.tsx
> +    const onNextPress = useCallback(() => {
rename to `onSubmit`

2022-09-02 15:43 UTC, Reykjavik151 commented on app/screens/Onboarding/Parents/SignUp/SignUpAvatar/SignUpAvatar.data.ts
> +export const SING_UP_CAROUSEL_DATA: ICarouselItem[] = [
ReadonlyArray

2022-09-02 15:53 UTC, emberglaz commented on app/screens/Onboarding/Parents/SignUp/SignUpAvatar/SignUpAvatar.data.ts
> +export const SING_UP_CAROUSEL_DATA: ICarouselItem[] = [
`SING_UP_CAROUSEL`

2022-09-02 15:53 UTC, emberglaz commented on app/screens/Onboarding/Parents/OnboardingCarousel/OnboardingCarousel.data.ts
> +export const CHARMS_CAROUSEL: ICarouselItem[] = [
in another pr

2022-09-02 17:28 UTC, Reykjavik151 requested changes

2022-09-02 17:28 UTC, Reykjavik151 commented on app/screens/Onboarding/Parents/LanguageSelection/LanguageSelection.data.ts
> +export const LANGUAGES: IRadioButtonListItem[] = [
ReadonlyArray is needed, so leave only `id` and `title`
The `isActive` you need map later with these Readonly values

2022-09-02 17:28 UTC, Reykjavik151 commented on app/screens/Onboarding/Parents/OnboardingCarousel/OnboardingCarousel.data.ts
> +export const CHARMS_CAROUSEL: ICarouselItem[] = [
ReadonlyArray?

2022-09-02 17:57 UTC, Reykjavik151 commented
Also, please fix your typing mistake in the PR naming -- `carousel`

2022-09-06 11:14 UTC, Reykjavik151 approved these changes

2022-09-06 11:14 UTC, merged