feat(emoji-buttons): EmojiButtons component UX
apartofme/apartofme-saferplace pull request #36
Opened 2022-09-05 13:32 UTC by akhlivnoy

2022-09-05 15:52 UTC, emberglaz requested changes

2022-09-05 15:52 UTC, emberglaz commented on app/components/EmojiButtons/EmojiButtons.data.ts
> +  veryOk = 'veryOk',
```
VeryStressed = 'veryStressed',
   Neutral = 'neutral',
   Ok = 'ok',
   Stressed = 'stressed',
   Worried = 'worreid',
   VeryOk = 'veryOk',
```

2022-09-06 13:18 UTC, emberglaz approved these changes

2022-09-06 13:40 UTC, Reykjavik151 approved these changes

2022-09-06 13:40 UTC, merged