feat(grown-ups-guide): UX & logic & navigation
apartofme/apartofme-saferplace pull request #47
Opened 2022-09-06 17:29 UTC by VladislavRiabko

- add ButtonsMenu screen 
- add ButtonsMenu to Menu stack

2022-09-07 10:06 UTC, emberglaz requested changes

2022-09-07 10:06 UTC, emberglaz commented on app/navigation/stacks/menuStackNavigator.tsx
> +import { IButtonsMenuItem } from '../../screens/Menu/ButtonsMenu/ButtonsMenu.data';
import from screens

2022-09-07 10:06 UTC, emberglaz commented on app/screens/Menu/ButtonsMenu/ButtonsMenu.tsx
> +import { MenuButton } from '../components';
refactor imports

2022-09-07 10:06 UTC, emberglaz commented on app/screens/Menu/ButtonsMenu/ButtonsMenu.tsx
> +  const onMenuItemPress = useCallback((item: IButtonsMenuItem) => {}, []);
use noop

2022-09-07 10:06 UTC, emberglaz commented on app/screens/Menu/MainMenu/MainMenu.data.ts
> +  Guide = 'GrownUpGuide',
Guide = 'grownUpGuide',

2022-09-07 10:06 UTC, emberglaz commented on app/screens/Menu/MainMenu/MainMenu.tsx
> +          // navigation.navigate(item.type);
commented

2022-09-07 10:06 UTC, emberglaz commented on app/screens/Menu/MainMenu/MainMenu.tsx
>    // TODO: change when adding screens
`// TODO: uncomment when adding screens`

2022-09-07 13:36 UTC, emberglaz requested changes

2022-09-07 13:36 UTC, emberglaz commented on app/screens/Menu/MainMenu/MainMenu.data.ts
> +//* screens name
`//* This enum is used for navigation so names must be capitalized`

2022-09-08 08:49 UTC, Reykjavik151 requested changes
But why did you delete ParentsGuide screen?

2022-09-08 11:07 UTC, VladislavRiabko commented
> But why did you delete ParentsGuide screen?

We change naming and I remove it in this pr. But I save it in next pr.

2022-09-09 09:28 UTC, Reykjavik151 approved these changes

2022-09-09 09:28 UTC, merged