feat(notification-settings-screen): UX & navigation & redux flow
apartofme/apartofme-saferplace pull request #49
Opened 2022-09-07 11:44 UTC by VladislavRiabko

- add isNotificationAllow to state 
- add setNotificationAllow action 
- add ExtendedSwitch component 
- add MenuSwitch component 
- add NotificationSettings screen UX

2022-09-08 08:52 UTC, Reykjavik151 requested changes

2022-09-08 08:52 UTC, Reykjavik151 commented on app/redux/slices/settingsSlice.ts
> +  isNotificationAllow: boolean;
rename to `isNotificationsEnabled`
all settings options should be with suffix `Enabled` for switches

2022-09-08 08:52 UTC, Reykjavik151 commented on app/redux/types/settingsTypes.ts
> +  isNotificationAllow: boolean;
The same as above

2022-09-08 08:52 UTC, Reykjavik151 commented on app/redux/types/settingsTypes.ts
> +export type INotificationAllowActionPayload = PayloadAction<{
rename to `ChangeNotificationSetting`

2022-09-08 08:52 UTC, Reykjavik151 commented on app/screens/Menu/NotificationSettings/NotificationSettings.tsx
> +    );
the same as above

2022-09-08 08:52 UTC, Reykjavik151 commented on app/screens/Menu/NotificationSettings/NotificationSettings.tsx
> +    }, [isNotificationAllow, setIsNotificationAllow, dispatch]);
the same as above

2022-09-08 08:52 UTC, Reykjavik151 commented on app/screens/Menu/NotificationSettings/NotificationSettings.tsx
> +            title={t('screens.menu.notification_settings.allow_notifications')}
the same as above (naming)

2022-09-08 08:52 UTC, Reykjavik151 commented on app/screens/Menu/components/MenuSwitch/MenuSwitch.tsx
> +export const MenuSwitch: React.FC<IMenuSwitchProps> = ({
Maybe name it as `MenuSwitchRow`?

2022-09-09 09:53 UTC, Reykjavik151 requested changes

2022-09-09 09:53 UTC, Reykjavik151 commented on app/redux/types/settingsTypes.ts
> +};
rename to `setSettings`

2022-09-09 12:05 UTC, emberglaz requested changes

2022-09-09 12:05 UTC, emberglaz commented on app/redux/slices/settingsSlice.ts
> +    },
refactor

2022-09-09 12:05 UTC, emberglaz commented on app/redux/types/settingsTypes.ts
> +}>;
the same

2022-09-09 12:05 UTC, emberglaz commented on app/redux/slices/settingsSlice.ts
> -import { ISettingsActionPayload } from '../types';
refactor inputs

2022-09-12 09:10 UTC, emberglaz approved these changes

2022-09-12 09:29 UTC, merged