feat(feedback-success-screen): UX & navigation
apartofme/apartofme-saferplace pull request #50
Opened 2022-09-07 11:49 UTC by VladislavRiabko

- add FeedbackSuccess screen

2022-09-07 12:06 UTC, Reykjavik151 requested changes

2022-09-07 12:06 UTC, Reykjavik151 commented on app/screens/Menu/FeedbackSuccess/FeedbackSuccess.styles.ts
> +  },
rename it with lowercase: `subtitle`

2022-09-07 13:33 UTC, emberglaz requested changes

2022-09-07 13:33 UTC, emberglaz commented on app/screens/Menu/FeedbackSuccess/FeedbackSuccess.tsx
> +import { styles } from './FeedbackSuccess.styles';
refactor imports

2022-09-08 08:53 UTC, Reykjavik151 approved these changes

2022-09-08 08:53 UTC, merged