feat(grown-ups-guide-menu-screen): UX & navigation
apartofme/apartofme-saferplace pull request #58
Opened 2022-09-10 10:21 UTC by VladislavRiabko

- add GrownUpsGuide screen 
- add AboutCharms data 
- refactor AboutCharms screen

2022-09-11 08:56 UTC, emberglaz requested changes

2022-09-11 08:56 UTC, emberglaz commented on app/screens/Menu/AboutCharm/AboutCharm.data.ts
> +    type: AboutCharmsMenuType.TheCharmOfTheSlowWind,
add localizations key

2022-09-11 10:36 UTC, Reykjavik151 requested changes

2022-09-11 10:36 UTC, Reykjavik151 commented on app/screens/Menu/AboutCharm/AboutCharm.data.ts
> +export const ABOUT_CHARMS_SCREEN_DATA: AboutCharmsMenuItem[] = [
Readonly

2022-09-11 10:36 UTC, Reykjavik151 commented on app/screens/Menu/AboutCharm/AboutCharm.tsx
> +      })}
What is this `if statement` doing? Non-readable logic, refactor

2022-09-12 09:08 UTC, emberglaz approved these changes

2022-09-12 09:36 UTC, merged