feat(elixir-double-interaction-screen): UX & logic
apartofme/apartofme-saferplace pull request #73
Opened 2022-09-15 10:36 UTC by VladislavRiabko

- add ElixirDoubleInteraction screen
- add double press logic

2022-09-16 08:25 UTC, emberglaz requested changes

2022-09-16 08:25 UTC, emberglaz commented on app/screens/Reusable/ElixirDoubleInteractionScreen/ElixirDoubleInteraction.styles.ts
> +export interface IDialogscreenStyles {
rename

2022-09-16 08:25 UTC, emberglaz commented on app/screens/Reusable/ElixirDoubleInteractionScreen/ElixirDoubleInteraction.styles.ts
> +export const styles = StyleSheet.create<IDialogscreenStyles>({
the same

2022-09-19 09:05 UTC, Reykjavik151 requested changes

2022-09-19 09:05 UTC, Reykjavik151 commented on app/screens/Reusable/ElixirDoubleInteractionScreen/ElixirDoubleInteraction.tsx
> +            onTouchEnd={() => setIsAdultPress(false)}
move these functions to useCallbacks and reuse it between your JSX

2022-09-20 15:18 UTC, merged