feat(felt-recent-screen): UX & selection logic
apartofme/apartofme-saferplace pull request #75
Opened 2022-09-15 14:03 UTC by VladislavRiabko

- add FeltRecent screen 
- add FeltRecentItem component 
- add localization

2022-09-16 08:29 UTC, emberglaz requested changes

2022-09-16 08:29 UTC, emberglaz commented on app/screens/Reusable/FeltRecent/FeltRecent.data.ts
> +}
move to types

2022-09-16 08:29 UTC, emberglaz commented on app/screens/Reusable/FeltRecent/components/FeltRecentItem/FeltRecentItem.tsx
> +import { useTranslation } from 'react-i18next';
refactor

2022-09-16 08:29 UTC, emberglaz commented on app/services/localization/languages/en.ts
> +    },
it`s 
```
labels : {
emoji: {
anger: 'Anger',
...
}
.....
}
```

2022-09-19 09:06 UTC, Reykjavik151 approved these changes

2022-09-19 09:08 UTC, merged